version: "3"
services:
  app:
    build: .
    ports:
      - "8001:80"
    volumes:
      - ./app:/srv/app


      # Configuration for docker image


      # docker ps -> Gives list of all images
      # docker compose up